services:
  site-stream:
    build: .
    container_name: site-stream
    restart: unless-stopped
    tmpfs: /tmp
    tty: true
    environment:
      - SITE_URL=https://google.com
      - STREAM_KEY=
      - SCREEN_W=1920
      - SCREEN_H=1080
